In [7]:
import numpy as np
import random
import math
import matplotlib.pyplot as plt

In [8]:
alp = 0.5

In [9]:
arr = [[0,0],[0,1],[1,0],[1,1]]
inp = np.array(arr)
inp

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [10]:
arr1 = [[0,0],[0,0],[0,0],[1,1]] 
out = np.array(arr1)
out

array([[0, 0],
       [0, 0],
       [0, 0],
       [1, 1]])

In [11]:
perceptrons_weights = []
for i in range(6): 
    perceptrons_weights.append(random.randrange(45,55))
lw1 = perceptrons_weights[:2]
lw2 = perceptrons_weights[2:4]
lw3 = perceptrons_weights[4:6]
wt = np.array([lw1,lw2,lw3]) 
wt

array([[46, 51],
       [48, 45],
       [51, 52]])

In [12]:
def multiply(perceptrons_weights,sigarray):  
    mul = perceptrons_weights*sigarray
    return mul

In [13]:
def sigmoid(x):
    z = 1/(1 + np.exp(-x))
    return z
vector = np.vectorize(sigmoid) 

for i in range(0,len(inp)):
    layer1 = vector(multiply(wt[0],inp[i])) #Values for layer1 (Input layer)
    layer2 = vector(multiply(wt[1],layer1)) #Values for layer2 (Hidden layer)
    layer3 = vector(multiply(wt[2],layer2)) #Values for layer3 (Output layer)
    
    #Backward Propagation
    
    er3 = (out[i] - layer3)*(np.ones(2) - layer3)*layer3*layer2 
    wt[2] = wt[2] + (alp * er3)
    er2 = (out[i] - layer3)*(np.ones(2) - layer3)* layer3 * wt[2] * (np.ones(2) - layer2) * layer2 * layer1 
    wt[1] = wt[1] + (alp * er2)
    er1 = (out[i] - layer3)*(np.ones(2) - layer3)*layer3*wt[2]*(np.ones(2) - layer2)*layer2*wt[1]*(np.ones(2) - layer1)*layer1*inp[i] 
    wt[0] = wt[0] + (alp * er1) 
print(wt)


[[46 51]
 [48 45]
 [51 52]]


In [14]:
sample = np.array([1,1]) 
sample

array([1, 1])

In [15]:
layer1 = vector(multiply(wt[0],sample))
layer2 = vector(multiply(wt[1],sample)) 
layer3 = vector(multiply(wt[2],sample)) 

In [16]:
layer3

array([1., 1.])

In [17]:
import tensorflow as tf
from tensorflow import keras

In [19]:
# Input arrays
a = np.array([0, 0, 1, 1])
b = np.array([0, 1, 0, 1])
# Output array
out = np.array([0, 0, 0, 1])
# Final input array is obtained after combining the input elements into a new array.
total_input = []

for i, j in zip(a, b):
    input1 = []
    input1.append(i)
    input1.append(j)
    total_input.append(input1)
    
total_input = np.array(total_input) #Final input array
total_input

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [20]:
x_train = []
y_train = []

for i, j in zip(total_input, opt):
    x_train.append(i)
    y_train.append(j)
    
x_train = np.array(x_train)
y_train = np.array(y_train)

In [27]:
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Sequential

model = keras.Sequential(name="my_sequential")
model.add(Input(shape = x_train[0].shape))
model.add(Dense(10, activation = "relu"))
model.add(Dense(10, activation = "relu"))
model.add(Dense(1, activation = "sigmoid"))
model.summary()

Model: "my_sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_14 (Dense)            (None, 10)                30        
                                                                 
 dense_15 (Dense)            (None, 10)                110       
                                                                 
 dense_16 (Dense)            (None, 1)                 11        
                                                                 
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [29]:
model.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = "binary_accuracy")

In [30]:
model.fit(x_train, y_train, epochs = 500)

Epoch 1/500
1/1 [==============================] - 3s 3s/step - loss: 0.6756 - binary_accuracy: 1.0000
Epoch 2/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6744 - binary_accuracy: 1.0000
Epoch 3/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6729 - binary_accuracy: 1.0000
Epoch 4/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6715 - binary_accuracy: 1.0000
Epoch 5/500
1/1 [==============================] - 0s 5ms/step - loss: 0.6701 - binary_accuracy: 1.0000
Epoch 6/500
1/1 [==============================] - 0s 7ms/step - loss: 0.6687 - binary_accuracy: 1.0000
Epoch 7/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6674 - binary_accuracy: 1.0000
Epoch 8/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6660 - binary_accuracy: 1.0000
Epoch 9/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6647 - binary_accuracy: 1.0000
Epoch 10/500
1/1 [==============================] - 0s 4ms/step -

1/1 [==============================] - 0s 4ms/step - loss: 0.5829 - binary_accuracy: 1.0000
Epoch 80/500
1/1 [==============================] - 0s 4ms/step - loss: 0.5816 - binary_accuracy: 1.0000
Epoch 81/500
1/1 [==============================] - 0s 3ms/step - loss: 0.5803 - binary_accuracy: 1.0000
Epoch 82/500
1/1 [==============================] - 0s 6ms/step - loss: 0.5791 - binary_accuracy: 1.0000
Epoch 83/500
1/1 [==============================] - 0s 3ms/step - loss: 0.5778 - binary_accuracy: 1.0000
Epoch 84/500
1/1 [==============================] - 0s 4ms/step - loss: 0.5764 - binary_accuracy: 1.0000
Epoch 85/500
1/1 [==============================] - 0s 4ms/step - loss: 0.5751 - binary_accuracy: 1.0000
Epoch 86/500
1/1 [==============================] - 0s 4ms/step - loss: 0.5737 - binary_accuracy: 1.0000
Epoch 87/500
1/1 [==============================] - 0s 5ms/step - loss: 0.5723 - binary_accuracy: 1.0000
Epoch 88/500
1/1 [==============================] - 0s 4ms/step - lo

1/1 [==============================] - 0s 3ms/step - loss: 0.4620 - binary_accuracy: 1.0000
Epoch 157/500
1/1 [==============================] - 0s 4ms/step - loss: 0.4602 - binary_accuracy: 1.0000
Epoch 158/500
1/1 [==============================] - 0s 3ms/step - loss: 0.4585 - binary_accuracy: 1.0000
Epoch 159/500
1/1 [==============================] - 0s 4ms/step - loss: 0.4567 - binary_accuracy: 1.0000
Epoch 160/500
1/1 [==============================] - 0s 4ms/step - loss: 0.4550 - binary_accuracy: 1.0000
Epoch 161/500
1/1 [==============================] - 0s 4ms/step - loss: 0.4532 - binary_accuracy: 1.0000
Epoch 162/500
1/1 [==============================] - 0s 3ms/step - loss: 0.4514 - binary_accuracy: 1.0000
Epoch 163/500
1/1 [==============================] - 0s 4ms/step - loss: 0.4497 - binary_accuracy: 1.0000
Epoch 164/500
1/1 [==============================] - 0s 3ms/step - loss: 0.4479 - binary_accuracy: 1.0000
Epoch 165/500
1/1 [==============================] - 0s 4ms/

1/1 [==============================] - 0s 4ms/step - loss: 0.3341 - binary_accuracy: 1.0000
Epoch 234/500
1/1 [==============================] - 0s 3ms/step - loss: 0.3325 - binary_accuracy: 1.0000
Epoch 235/500
1/1 [==============================] - 0s 4ms/step - loss: 0.3309 - binary_accuracy: 1.0000
Epoch 236/500
1/1 [==============================] - 0s 5ms/step - loss: 0.3292 - binary_accuracy: 1.0000
Epoch 237/500
1/1 [==============================] - 0s 3ms/step - loss: 0.3276 - binary_accuracy: 1.0000
Epoch 238/500
1/1 [==============================] - 0s 3ms/step - loss: 0.3260 - binary_accuracy: 1.0000
Epoch 239/500
1/1 [==============================] - 0s 5ms/step - loss: 0.3244 - binary_accuracy: 1.0000
Epoch 240/500
1/1 [==============================] - 0s 3ms/step - loss: 0.3228 - binary_accuracy: 1.0000
Epoch 241/500
1/1 [==============================] - 0s 4ms/step - loss: 0.3212 - binary_accuracy: 1.0000
Epoch 242/500
1/1 [==============================] - 0s 3ms/

1/1 [==============================] - 0s 4ms/step - loss: 0.2221 - binary_accuracy: 1.0000
Epoch 311/500
1/1 [==============================] - 0s 4ms/step - loss: 0.2209 - binary_accuracy: 1.0000
Epoch 312/500
1/1 [==============================] - 0s 4ms/step - loss: 0.2197 - binary_accuracy: 1.0000
Epoch 313/500
1/1 [==============================] - 0s 4ms/step - loss: 0.2185 - binary_accuracy: 1.0000
Epoch 314/500
1/1 [==============================] - 0s 3ms/step - loss: 0.2173 - binary_accuracy: 1.0000
Epoch 315/500
1/1 [==============================] - 0s 3ms/step - loss: 0.2161 - binary_accuracy: 1.0000
Epoch 316/500
1/1 [==============================] - 0s 5ms/step - loss: 0.2149 - binary_accuracy: 1.0000
Epoch 317/500
1/1 [==============================] - 0s 3ms/step - loss: 0.2137 - binary_accuracy: 1.0000
Epoch 318/500
1/1 [==============================] - 0s 4ms/step - loss: 0.2125 - binary_accuracy: 1.0000
Epoch 319/500
1/1 [==============================] - 0s 4ms/

1/1 [==============================] - 0s 4ms/step - loss: 0.1453 - binary_accuracy: 1.0000
Epoch 388/500
1/1 [==============================] - 0s 7ms/step - loss: 0.1446 - binary_accuracy: 1.0000
Epoch 389/500
1/1 [==============================] - 0s 4ms/step - loss: 0.1437 - binary_accuracy: 1.0000
Epoch 390/500
1/1 [==============================] - 0s 5ms/step - loss: 0.1430 - binary_accuracy: 1.0000
Epoch 391/500
1/1 [==============================] - 0s 3ms/step - loss: 0.1422 - binary_accuracy: 1.0000
Epoch 392/500
1/1 [==============================] - 0s 2ms/step - loss: 0.1414 - binary_accuracy: 1.0000
Epoch 393/500
1/1 [==============================] - 0s 5ms/step - loss: 0.1407 - binary_accuracy: 1.0000
Epoch 394/500
1/1 [==============================] - 0s 4ms/step - loss: 0.1400 - binary_accuracy: 1.0000
Epoch 395/500
1/1 [==============================] - 0s 4ms/step - loss: 0.1392 - binary_accuracy: 1.0000
Epoch 396/500
1/1 [==============================] - 0s 6ms/

1/1 [==============================] - 0s 4ms/step - loss: 0.0976 - binary_accuracy: 1.0000
Epoch 465/500
1/1 [==============================] - 0s 4ms/step - loss: 0.0971 - binary_accuracy: 1.0000
Epoch 466/500
1/1 [==============================] - 0s 5ms/step - loss: 0.0966 - binary_accuracy: 1.0000
Epoch 467/500
1/1 [==============================] - 0s 3ms/step - loss: 0.0961 - binary_accuracy: 1.0000
Epoch 468/500
1/1 [==============================] - 0s 4ms/step - loss: 0.0957 - binary_accuracy: 1.0000
Epoch 469/500
1/1 [==============================] - 0s 5ms/step - loss: 0.0952 - binary_accuracy: 1.0000
Epoch 470/500
1/1 [==============================] - 0s 4ms/step - loss: 0.0947 - binary_accuracy: 1.0000
Epoch 471/500
1/1 [==============================] - 0s 6ms/step - loss: 0.0943 - binary_accuracy: 1.0000
Epoch 472/500
1/1 [==============================] - 0s 3ms/step - loss: 0.0938 - binary_accuracy: 1.0000
Epoch 473/500
1/1 [==============================] - 0s 5ms/

In [31]:
model.predict(x_train)

1/1 [==============================] - 0s 253ms/step


array([[0.03947314],
       [0.15440257],
       [0.01976345],
       [0.9053882 ]], dtype=float32)